### ISSUE TITLE
Don't set cache-control and expires headers.

### ISSUE THREAD

**Issue by ADmad** [thephpleague/glide-cake#1]
Let users set caching related headers as per their needs.

**Comment by reinink** [comment]
Hmm, don't you think it makes sense to have some sensible defaults, and then the user can remove/update them further if they'd like to?

**Comment by ADmad** [comment]
I would prefer it to be opt-in instead of opt-out but I guess sensible defaults are fine. I'll just use my own response factory :)

**Comment by reinink** [comment]
Out of curiosity, what headers did you not want?

**Comment by ADmad** [comment]
None, during app development :)

**Comment by ADmad** [comment]
I would suggest adding a check for `\Cake\Core\Configure::read('debug')` and set the caching headers only if that call returns false.
